---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cra-criticality-score
spec:
  params:
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"
    #- name: git_token
    #  description: git token for criticality score
    #  default: "secure-properties"       
  #results:
  #  - name: status
  #    description: status of bom task, possible value are-success|failure
  #  - name: evidence-store
  #    description: filepath to store bom task evidence
  stepTemplate:
    env:
      - name: PIPELINE_RUN_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)

  steps:
    - name: criticality-score
      image: gcr.io/cra-criticality/critical-score:dev
      workingDir: "/artifacts"
      env: 
        - name: GITHUB_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: secure-properties
              key: git_token
      volumeMounts:
      # - mountPath: /steps
      #    name: steps-volume
        - mountPath: /secrets
          name: secure-properties
      command: ["/bin/bash", "-c"]
      args:
        - |        
          echo "";
          echo -e "git_token from Secrets is >>";
          echo $GITHUB_AUTH_TOKEN
  workspaces:
    - name: artifacts
      mountPath: /artifacts
  volumes:
    - name: steps-volume
      emptyDir: {}
    #- name: secure-properties
    #  secret:
    #    secretName: $(params.git_token)